export default ACTION_TYPES = {
    USER_OPERATIONS : {
        NEW_NAME: 'new user name',
        LOGGED_ON : 'user logged on',
        LOGGED_OFF : 'user logged off',
    },
    NEWORDER_REFRESH: "NEWORDER_REFRESH",
    NEWORDER_REFRESH_FAIL: "NEWORDER_REFRESH_FAIL",
    NEWORDER_REFRESH_SUCCESS: "NEWORDER_REFRESH_SUCCESS",
    NEWORDERDETAIL_LOAD: "NEWORDERDETAIL_LOAD",
    NEWORDERDETAIL_LOAD_FAIL: "NEWORDERDETAIL_LOAD_FAIL",
    NEWORDERDETAIL_LOAD_SUCCESS: "NEWORDERDETAIL_LOAD_SUCCESS",
    INPROGRESSORDER_REFRESH: "INPROGRESSORDER_REFRESH",
    INPROGRESSORDER_REFRESH_FAIL: "INPROGRESSORDER_REFRESH_FAIL",
    INPROGRESSORDER_REFRESH_SUCCESS: "INPROGRESSORDER_REFRESH_SUCCESS",
    INPROGRESSORDERDETAIL_LOAD: "INPROGRESSORDERDETAIL_LOAD",
    INPROGRESSORDERDETAIL_LOAD_FAIL: "INPROGRESSORDERDETAIL_LOAD_FAIL",
    INPROGRESSORDERDETAIL_LOAD_SUCCESS: "INPROGRESSORDERDETAIL_LOAD_SUCCESS",
}